--ALTER TABLE - alterando sua tabela de dado

SELECT * INTO TEMP FROM DBO.ALUNOS
SELECT * FROM TEMP

--ALTER TABLE
ALTER TABLE TEMP ADD CPF VARCHAR(14) ;
ALTER TABLE TEMP DROP COLUMN CPF

--UPDATE
UPDATE TEMP 
SET CPF = '340.678.224-35'
WHERE ID_ALUNO = 1 

