--DELETE - apagando dados das tabelas

SELECT *
INTO DBO.TBDELETE
FROM DBO.CURSOS

DELETE FROM DBO.TBDELETE 
	WHERE nome_curso LIKE '%AVANÇADO%'

SELECT * FROM DBO.TBDELETE

SELECT * 
	INTO ALUNOSTEMP FROM Alunos

--DELETE COM SELECT

DELETE FROM ALUNOSTEMP
WHERE id_aluno in 
(
		SELECT a.id_aluno
		FROM ALUNOSTEMP A
		INNER JOIN AlunosXTurmas T ON T.id_aluno = A.id_aluno
)

-- INSERT COM SELECT
SELECT * FROM ALUNOSTEMP 

INSERT INTO ALUNOSTEMP (ID_ALUNO, NOME, DATA_NASCIMENTO, SEXO, DATA_CADASTRO, LOGIN_CADASTRO)
SELECT * FROM ALUNOS

SET IDENTITY_INSERT ALUNOSTEMP ON