--Funções de Texto FORMAT, LEFT, RIGHT, LEN, LOWER e UPPER
--DECLARAÇÃO DE FUNÇOES

DECLARE @DT DATETIME = CONVERT(CHAR,GETDATE(),103)
SELECT  FORMAT(@DT , 'D', 'PT-BR') AS AMERICANO 

--FORMATANDO PARA PADRÃO DETERMNINADO
SELECT FORMAT(1001500,'#-###-###') AS 'COD-PRODUTO'

--LEFT EXTRAI CARACTERE A ESQUERDA
SELECT LEFT('SEBASTIAO SANTOS',8)
SELECT LEFT('5C',1)

--RIGTH EXTRAI CARACTERE A DIREITA
SELECT RIGHT('SEBASTIAO SANTOS',8)
SELECT LEFT(NOME,2) + RIGHT(NOME,5) FROM ALUNOS

--LEN TAMANHO DA STRING
SELECT LEN(NOME) AS 'TAMANHO STRING',NOME FROM ALUNOS
SELECT MAX(LEN(NOME)) AS 'TAMANHO STRING' FROM ALUNOS

--UPPER CONVERTE CARACTERES PARA MAIUSCULO
SELECT UPPER('sebastião santos')

--LOWER CONVERTE CARACTERES PARA MINUSCULO
SELECT LOWER('SEBASTIAO WAGNER M. SANTOS')
