--Funções de Data (getdate, datediff, dateadd e Datepart)
SELECT GETDATE()--GETDATE() PEGA DATA E HORA ATUAL
SELECT CONVERT(CHAR,GETDATE(),103)--CONVERTE PARA FORMATO DD/MM/YYYY
SELECT CONVERT(CHAR,GETDATE(),102)--CONVERTE PARA FORMATO AAA.MM.DD
SELECT CONVERT(CHAR,GETDATE(),3)--CONVERTE PARA FORMATO DD/MM/AA TABELA ANSI SQL
SELECT DAY(GETDATE()) AS DIA--PEGA O DIA
SELECT MONTH(GETDATE()) AS MES--PEGA O MES
SELECT YEAR(GETDATE()) AS ANOC

--DATEPART
SELECT DATEPART(YEAR,DATA_NASCIMENTO) FROM DBO.Alunos--PEGA O ANO
SELECT  DISTINCT DATEPART(MONTH,DATA_NASCIMENTO) FROM DBO.Alunos ORDER BY 1--PEGA O MES

--DATEADD PARA FAZER CALCULO COM A DATA
SELECT DATEADD(YEAR, 2, GETDATE())-- ADD 2 ANOS
SELECT CONVERT(DATETIME,DATEADD(HOUR,3,GETDATE()))

--DATEDIFF DIFERENÇA ENTRE DATAS
SELECT DATEDIFF(DAY,GETDATE(), DATEADD(YEAR,4,GETDATE()))