--FUNÇÃO ASCII RETORNA O NUMERO DO CARACTERE ASCII
SELECT ASCII('a')
SELECT ASCII('A')

--FUNÇÃO NCHAR RETORNA QUAL O CARACTERE A PARTIR DE UM NUMERO
SELECT NCHAR('65')
SELECT NCHAR('97')

--CHARINDEX PESQUISA UM CARACTERE EM UMA SEQUENCIA DE ATE 8MIL CARACTERES
SELECT CHARINDEX('A', 'SEBASTIAO')
SELECT CHARINDEX('A', 'SEBASTIAO' ,5)
SELECT CHARINDEX('R', 'SEBASTIAO WAGNER')

SELECT  CHARINDEX('I',NOME) FROM DBO.ALUNOS

SELECT NOME, CHARINDEX('Passarelli', nome)
FROM DBO.ALUNOS
WHERE CONVERT(INT, CHARINDEX('Passarelli',NOME, 1) ) > 0

SELECT A.NOME, CHARINDEX('Passarelli', A.nome, 1)
FROM DBO.ALUNOS A
WHERE CHARINDEX('Passarelli', A.nome, 1) <> '0'

--CONCAT CONCATENA STRINGS
SELECT CONCAT('SEBASTIAO', ' ', 'SANTOS')

SELECT CONCAT(A.NOME, ' ', C.NOME_CURSO) AS 'NOME DO ALUNO - CURSO'
FROM ALUNOS A
	INNER JOIN AlunosXTurmas AT ON AT.id_aluno = A.id_aluno
	INNER JOIN Turmas T ON T.id_turma = AT.id_turma
	INNER JOIN Cursos C ON C.id_curso = T.id_curso


