--IF ... ELSE - Estruturas de decisão

select * INTO tTEMP from ALUNOS

IF DATENAME(weekday, Getdate()) IN ('sabado','Domingo')
	select 'Estamos em um fim de semana'
	ELSE
	select CONCAT('Estamos em um dia de semana hoje é dia ', datename(week,GETDATE()))


-- VARIAVEIS GLOBAIS DO SQL
SELECT @@SERVERNAME
SELECT @@LANGUAGE
SELECT @@LANGID --ID LANGUAGEM
SELECT @@TRANCOUNT -- TRANSAÇÃO QUE ESTA ATIVO

IF @@LANGUAGE <> 'PORTUGUES (BRASIL)'
	SELECT CONCAT('TODAY IS ', DATENAME(DAY,GETDATE()),'/', DATENAME(MONTH,GETDATE() ))
	ELSE
	SELECT 'HOJE É ' +   DATENAME(DAY,GETDATE())


--OBJECT_ID VERIFICA SE UM OBJETO EXISTE

IF OBJECT_ID('DBO.ALUNOS') IS NULL
	SELECT 'ESTA TABELA NÃO EXISTE'
	ELSE
	exec sp_columns ALUNOS

-------------------------------------------------------------------------------------
DECLARE @VIDADEMAX INT
DECLARE @VPARAM INT
SET @VIDADEMAX = 17
SET @VPARAM = 25

IF @VIDADEMAX >= @VPARAM
	SELECT NOME,DATA_NASCIMENTO, DATEDIFF(YEAR, data_nascimento, GETDATE()) IDADE
	FROM tTEMP
	WHERE DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) >= @VIDADEMAX
	ORDER BY 3 ASC
	ELSE
	SELECT NOME,data_nascimento, DATEDIFF(YEAR, data_nascimento, GETDATE()) IDADE
	FROM tTEMP
	WHERE DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) <= @VIDADEMAX
	ORDER BY 3 ASC;

	