--INSERTs e suas variações

SELECT * FROM ALUNOS

CREATE SEQUENCE SEQ_ALUNOS
	START WITH 4
	INCREMENT BY 1

SELECT NEXT VALUE FOR SEQ_ALUNOS

--IDENTIFICAR CAMPOS EM TABELAS
EXEC SP_COLUMNS ALUNOS

--INSERT COM DESCRIÇÃO DOS CAMPOS
--EXEMPLO 1
INSERT INTO dbo.Alunos
      (id_aluno, nome, data_nascimento, 
	   sexo, data_cadastro, login_cadastro)
VALUES
      (next value for seq_Alunos, 'Alessandro Trovato Andrade', GETDATE(),
	   'M', getdate(), 'ALESS');

--EXEMPLO 2
DECLARE @ID INT;
	SELECT @ID = MAX(ID_CURSO)+1 FROM DBO.Cursos --VERIFICA QUAL O ULTIMO REGISTRO
INSERT INTO CURSOS
	(id_curso, nome_curso, data_cadastro,login_cadastro)
	VALUES
	(@ID, 'VBA AVANÇADO 3', GETDATE(), 'SEBA')
--EM CASO DE ERRO USAR O SET
SET IDENTITY_INSERT CURSOS ON --LIGAR O INSERT_IDENTITY
SET IDENTITY_INSERT CURSOS OFF --DESLIGAR O INSERT_IDENTITY

--INSERT COM CRIAÇÃO DE TABELA
SELECT * 
	INTO DBO.NOVA_TABELA
	FROM DBO.Cursos;

SELECT * FROM DBO.NOVA_TABELA

--DELETANDO TODAS OS REGISTROS DA TABELA
DELETE FROM DBO.NOVA_TABELA

INSERT INTO DBO.NOVA_TABELA
	(id_curso, nome_curso, data_cadastro, login_cadastro)
	SELECT * FROM SQL_DB_1.dbo.Cursos --WHERE nome_curso LIKE '%VBA%'
