--Funções de Texto LTRIM, RTRIM, PATINDEX, REPLACE, REPLICATE e REVERSE
--FUNÇÃO LTRIM
SELECT LTRIM('   SEBASTIAO SANTOS')

DECLARE @VARTEXTO VARCHAR(50)
	SET @VARTEXTO = '   ESSE É UM TESTE DO LTRIM'
	SELECT LTRIM(@VARTEXTO)

--FUNÇÃO RTRIM
SELECT RTRIM('SEBASTIAO SANTOS        ')
SELECT LEN(RTRIM('SEBASTIAO SANTOS       '))

DECLARE @VARTEXTO2 VARCHAR(50)
	SET @VARTEXTO2 = 'TESTANDO TEXTO COM RTRIM     '
	SELECT RTRIM(@VARTEXTO2)

--FUNÇÃO PATINDEX RETORNA A POSIÇÃO DA PRIMEIRA OCORRENCIA DE UM PADRÃO
SELECT PATINDEX('%NT%', 'SEBASTIAO SANTOS') -- NÃO IMPORTA SE A STRING ESTA NO INICIO OU FIM
SELECT PATINDEX('%A', 'QUARTA') --RETORNA QUANDO NO FIM DA STRING
SELECT PATINDEX('A%', 'ARMANDO')--RETORNA QUANDO NO INICIO DA STRING

DECLARE @VARTEXTO3 VARCHAR(50)
	SET @VARTEXTO3 = 'TESTANDO UMA SUBSTRING'
--SELECT SUBSTRING(@VARTEXTO3, 1, 7)
SELECT SUBSTRING(@VARTEXTO3, PATINDEX('%UMA%', @VARTEXTO3),3) 

--REPLACE SUBSTITUI UM CARACTERE DE UMA STRING
SELECT REPLACE('SEBASTIAO SANTOS', 'A', 'X') --1 O QUE EU PROCURO 2 TROCA POR
SELECT REPLACE(REPLACE('SEBASTIAO SANTOS', 'A', 'X'), 'O', '?')

SELECT A.NOME, A.DATA_NASCIMENTO, REPLACE(REPLACE(A.SEXO, 'M', ',MASCULINO'), 'F','FEMENINO') AS SEXO
	FROM ALUNOS A

DECLARE @CPF VARCHAR(15)
	SET @CPF = '340.224.678-35'
SELECT  REPLACE(REPLACE(@CPF,'.',''),'-','') AS CPF

--REPLICATE REPLICA UMA STRING 
SELECT REPLICATE('X',20)

SELECT NOME + REPLICATE('X',50 - LEN(NOME))
FROM ALUNOS

--REVERSE REVERTE UMA STRING
SELECT  REVERSE('SEBASTIAO SANTOS')






