--SEQUENCES - Criar, Alterar e Apagar
SELECT MAX(ID_ALUNO) + 1 FROM ALUNOS --VERIFICAR QUAL O ULTIMO REGISTRO

--SEQUENCES
CREATE SEQUENCE SEQ_TESTE01;
SELECT NEXT VALUE FOR SEQ_TESTE01

--TIPOS DE INCREMENTO
--SMALLINT INTERVALO DE -32.768 A 32.767
--TINYINT INTERVALO DE 0 A 255
--INT INTERVALO DE -2.147.483.648 A 2.147.483.647
--BIGINT INTERVALO DE -9.223.372.036.854.775.808 A 9.223.372.036.854.775.807 ** PADRÃO
-- DECIMAL E NUMERIC COM ESCALA DE 0

CREATE SEQUENCE SEQ_TESTE2
	 AS NUMERIC
	 START WITH 1
	 INCREMENT BY 1;
SELECT NEXT VALUE FOR SEQ_TESTE2

CREATE SEQUENCE SEQ_TESTE3
	 AS NUMERIC
	 START WITH 100
	 INCREMENT BY -1;
SELECT NEXT VALUE FOR SEQ_TESTE3

CREATE SEQUENCE SEQ_TESTE4
	 START WITH 1
	 INCREMENT BY 1
	 MINVALUE 1
	 MAXVALUE 1000
	 CYCLE --QUANDO CHEGAR A 1000 VOLTA PARA O 1
	 CACHE 3
SELECT NEXT VALUE FOR SEQ_TESTE4

--APAGAR SEQUENCES
DROP SEQUENCE SEQ_TESTE4

--REINICIAR UMA SEQUENCE
ALTER SEQUENCE SEQ_TESTE4 RESTART WITH 1


SELECT * FROM SYS.sequences WHERE NAME = 'SEQ_TESTE4' --SYS É O OWNER DOS OBJETOS DO SQL

