--Funções de Texto STRING_AGG, SPACE e STUFF

--SPACE GERA UM CONJUNTO DE ESPAÇO
SELECT 'SEBASTIÃO SANTOS ' + SPACE(25)
SELECT 'SEBASTIÃO SANTOS ' + SPACE(25) + 'X'

DECLARE @NOME VARCHAR(50)
	SET @NOME = 'SEBASTIÃO WAGNER MACEDO DOS SANTOS'
SELECT @NOME + SPACE(50 - LEN(@NOME))

SELECT A.NOME + SPACE(60 - LEN(A.NOME)) + A.SEXO, LEN(NOME + SPACE(60 - LEN(A.NOME)) + A.SEXO)
FROM ALUNOS A

--STRING_AGG CONCATENA OS VALORES DAS EXPRESSÕES DE CARACTERES E COLOCA OS VALORES DO SEPARADOR
--ENTRE ELES O SEPARADOR NÃO É ADD AO FINAL DA CADEIA DE CARACTERES
SELECT STRING_AGG(CONVERT(NVARCHAR(MAX), SEXO), ',') AS REGISTRO
FROM ALUNOS

SELECT STRING_AGG(CONVERT(NVARCHAR(MAX), ISNULL(SEXO,'N')), ',') AS REGISTRO
FROM ALUNOS

SELECT DATEPART(YEAR,DATA_NASCIMENTO) ANO,
	   STRING_AGG(CONVERT(NVARCHAR(MAX), ISNULL(SEXO, '0')), '-') AS REGISTRO
	FROM ALUNOS
GROUP BY DATEPART(YEAR,data_nascimento)

--STUFF SUBTITUI UMA STRING A PARTIR DE UMA POSIÇÃO DETERMINADA
SELECT STUFF('ABCDEF',3 , 2  , '12345678910') -- SUBSTITUI A PARTIR DA 3º POSIÇÃO E TROCA 2 CARACTERES

DECLARE @PROCURA VARCHAR(50)
DECLARE @SUBSTITUIR VARCHAR(50)
	SET @PROCURA = 'EU, XXXXXXXXXX, AUTORIZO....'
	SET @SUBSTITUIR = 'YAN PASSARELLI DOS SANTOS'
SELECT STUFF(@PROCURA,5 , 10, TRIM(@SUBSTITUIR)) RETORNO