--Funções de Texto SUBSTRING, TRIM, UPPER, LOWER, TRANSLATE, CASE WHEN e IIF

--FUNÇÃO SUBSTRING SELECIONA UM INTERVALO ESPECIFICO DE CARACTERES
SELECT SUBSTRING('SEBASTIÃO WAGNER M SANTOS', 3, 12) AS NOME 

SELECT SUBSTRING(A.nome, 1, 20) NOME_PARCIAL
FROM ALUNOS A

--CASE / WHEN
SELECT A.NOME,
	 CASE SUBSTRING(A.NOME, 1, CHARINDEX(' ', A.NOME, CHARINDEX(' ', A.NOME)+1))
		WHEN ' '
			THEN A.NOME
			ELSE
			SUBSTRING(A.NOME, 1, CHARINDEX(' ', A.NOME, CHARINDEX(' ', A.NOME)+1))
			END AS NOME_EXTRAIDO
	FROM Alunos A

--IIF 
SELECT A.nome,
	 iif(substring(a.nome, 1, charindex(' ', a.nome, charindex(' ', a.nome) +1))  = '',
		A.nome,
			SUBSTRING(A.nome, 1, CHARINDEX(' ', A.nome, CHARINDEX(' ', A.nome) + 1 )))
	FROM ALUNOS A;

--TRANSLATE SUBSTITUI CARACTERES 
SELECT TRANSLATE('2 * [3+4] / {7-2}', '[]{}','()()')

DECLARE @OPERACAO VARCHAR(15)
 SET @OPERACAO = '2*[3+4]/{7-2}';
 SELECT REPLACE
				(REPLACE(@OPERACAO,'[','('),
				']',')')

SELECT TRANSLATE('AB  CDEF','ABC','123')
SELECT STUFF('AB  CDEF',1,3,'123')

--TRIM ELIMINA ESPAÇO A DIREITA E A ESQUERDA
SELECT TRIM('    ALESSANDRO      TROVATO    ')

--WHILE
DECLARE @STRING VARCHAR(100);
	SET @STRING = 'SQL   SERVER    |';
WHILE CHARINDEX('  ',@STRING) > 0
BEGIN
		SET @STRING = REPLACE(@STRING, '  ', ' ')
END
SELECT @STRING;



--UPPER / LOWER
SELECT A.NOME, UPPER(A.NOME), LOWER(A.NOME) FROM ALUNOS A